# Dockerfile for building the wavefront-kubernetes-adapter for Linux.
FROM golang:1.9.2
RUN apt-get -qq update
RUN apt-get -qq install -y --no-install-recommends build-essential

ENV USER wavefronthq
ENV REPO wavefront-kubernetes-adapter

RUN mkdir -p $GOPATH/src/github.com/$USER
COPY . $GOPATH/src/github.com/$USER/$REPO
RUN cd $GOPATH/src/github.com/$USER/$REPO && make
