apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa-custom-metrics
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: cpu-request
      target:
        type: AverageValue
        averageValue: 1k
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wavefront-proxy
