apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa-custom-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wavefront-proxy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Object
      object:
        metric:
          name: cpu.usage_rate
        describedObject:
          apiVersion: networking.k8s.io/v1
          kind: Node
          name: gke-cluster-default-pool-f63db08a-xrdh
        target:
          type: Value
          value: 2k
